//$file${../../src/active~::ledblink.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: ledblink.qm
// File:  ${../../src/active~::ledblink.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${../../src/active~::ledblink.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#include "qpc.h"

#include "bsp.h"
#include "bsp_gpio.h"

/*============== ask QM to declare the buzzer class ================*/
//$declare${AOs::LEDblink} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::LEDblink} ...........................................................
typedef struct {
// protected:
    QActive super;

// public:
    QTimeEvt timeEvt;
} LEDblink;

// protected:
static QState LEDblink_initial(LEDblink * const me, void const * const par);
static QState LEDblink_LEDon(LEDblink * const me, QEvt const * const e);
static QState LEDblink_LEDoff(LEDblink * const me, QEvt const * const e);
//$enddecl${AOs::LEDblink} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

static LEDblink l_ledblink;
QActive * const LEDblink_AO = &l_ledblink.super;

void LEDblink_ctor(void) {
    LEDblink *me = (LEDblink *)LEDblink_AO;
    QActive_ctor(&me->super, Q_STATE_CAST(&LEDblink_initial));

    QTimeEvt_ctorX(&me->timeEvt, &me->super, LEDBLINK_TIMEOUT_SIG, 0U);
}

/*============== ask QM to define the buzzer class ================*/
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::LEDblink} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::LEDblink} ...........................................................

//${AOs::LEDblink::SM} .......................................................
static QState LEDblink_initial(LEDblink * const me, void const * const par) {
    //${AOs::LEDblink::SM::initial}
    return Q_TRAN(&LEDblink_LEDon);
}

//${AOs::LEDblink::SM::LEDon} ................................................
static QState LEDblink_LEDon(LEDblink * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::LEDblink::SM::LEDon}
        case Q_ENTRY_SIG: {
            bsp_green_led_on();
            QTimeEvt_armX(&me->timeEvt, 1500, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::LEDblink::SM::LEDon::LEDBLINK_TIMEOUT}
        case LEDBLINK_TIMEOUT_SIG: {
            status_ = Q_TRAN(&LEDblink_LEDoff);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::LEDblink::SM::LEDoff} ...............................................
static QState LEDblink_LEDoff(LEDblink * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::LEDblink::SM::LEDoff}
        case Q_ENTRY_SIG: {
            bsp_green_led_off();
            QTimeEvt_armX(&me->timeEvt, 100, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::LEDblink::SM::LEDoff::LEDBLINK_TIMEOUT}
        case LEDBLINK_TIMEOUT_SIG: {
            status_ = Q_TRAN(&LEDblink_LEDon);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::LEDblink} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

